name: booto_shawarma_pos
description: "Booto Shawarma Premium Android POS & Order Management Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local DB and state
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.0.5
  shared_preferences: ^2.2.2

  # Network and utilities
  http: ^1.1.0
  intl: ^0.18.1
  crypto: ^3.0.3
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
